### ISSUE TITLE
FIXME links in Docs

### ISSUE THREAD

**Issue by defbyte** [Threespot/tolaria#30]
Just wanted to flag the FIXME links in README.md

**Comment by defbyte** [comment]
FIXME links fixed, GitHub Page republished.

**Comment by defbyte** [comment]
Argh, on RubyDocs, the README that was slurped up still has the FIXME links

**Comment by csuhta** [comment]
Fixed with the 1.0.1 release: http://www.rubydoc.info/gems/tolaria
