### ISSUE TITLE
Remembering filtered lists enhancement

### ISSUE THREAD

**Issue by lfrancis** [Threespot/tolaria#38]
If a user needs to make edits to a filtered list of results, the user has to reapply the search filter each time a record is edited. Ideally a search filtered listing would be preserved and navigable until the filter is cleared or changed to another filter.

Example case:
A Tolaria implementation allows site users to flag objectionable content for an admin to vet. Admin filters by flag, gets a list of flagged items. Admin vets flagged entries, etc.

**Comment by csuhta** [comment]
This feature has been added with 1.2.0! https://github.com/Threespot/tolaria/releases/tag/v1.2.0
