### ISSUE TITLE
Change to a save-and-another/continue system

### ISSUE THREAD

**Issue by csuhta** [Threespot/tolaria#40]
Right now we redirect to the `index` screen on successful object save. Based on client and internal feedback, we should change this workflow:

- [ ] Put two buttons on the resource form, one should be <kbd>Save</kbd> and the other should be <kbd>Save & Add Another</kbd>
- [ ] If the user clicks <kbd>Save</kbd>, validate and redirect to the `show` screen on success.
- [ ] If the user clicks <kbd>Save & Add Another</kbd>, validate and redirect to the `new` screen on success.

This proposed change invalidates #38

**Comment by defbyte** [comment]
Taking discussion from Slack, and dropping it here (please @danielboggs and @tedw add your thoughts)

ok, let me flip this again - how about this (to solve button label issues and make this intuitive):

* `Save` always goes back to listing
* `Save & Review` goes to Inspect view

**Comment by defbyte** [comment]
:+1: this feature is looking good to me

**Comment by csuhta** [comment]
Ding! https://github.com/Threespot/tolaria/releases/tag/v1.2.0
