### ISSUE TITLE
Create dashboard with basic stats, similar to WordPress 📊

### ISSUE THREAD

**Issue by tedw** [Threespot/tolaria#60]
@csuhta @defbyte @danielboggs What do you all think about creating a dashboard that’s displayed when you first log into the admin? Here are some examples of things we could show:

- recently published items
- top authors
- analytics data
  - most viewed pages
  - most popular search terms
  - traffic sources
  - bounce rate
  - scroll depth
  - % of users on mobile devices
- social media activity
- recent comments

I think this would be a valuable feature for many organizations and would help WordPress users feel more at home with Tolaria.

**Comment by csuhta** [comment]
This is out of scope for Tolaria.

Tolaria is a generic CMS. You can manage any Rails model that you dream up. The app you're building may not be a syndication platform. You may not have authors, a publishing model, comments, top pages, etc. If you frequently build syndication platforms with Tolaria, you can add such a dashboard to your own base build or master projects. Those things are custom to your project needs.

However, as a quick fix for analytics dashboarding, you add analytics links to `Tolaria.config.help_links` to open a report you've built elsewhere.

**Comment by tedw** [comment]
Ok, makes sense. Will move to list of things to work on internally.
